export const permit3Abi = [
  { inputs: [], stateMutability: "nonpayable", type: "constructor" },
  {
    inputs: [{ internalType: "uint256", name: "deadline", type: "uint256" }],
    name: "AllowanceExpired",
    type: "error",
  },
  { inputs: [], name: "AllowanceLocked", type: "error" },
  { inputs: [], name: "ECDSAInvalidSignature", type: "error" },
  {
    inputs: [{ internalType: "uint256", name: "length", type: "uint256" }],
    name: "ECDSAInvalidSignatureLength",
    type: "error",
  },
  {
    inputs: [{ internalType: "bytes32", name: "s", type: "bytes32" }],
    name: "ECDSAInvalidSignatureS",
    type: "error",
  },
  {
    inputs: [{ internalType: "uint256", name: "amount", type: "uint256" }],
    name: "InsufficientAllowance",
    type: "error",
  },
  { inputs: [], name: "InvalidShortString", type: "error" },
  { inputs: [], name: "InvalidSignature", type: "error" },
  { inputs: [], name: "NonceAlreadyUsed", type: "error" },
  {
    inputs: [{ internalType: "address", name: "token", type: "address" }],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  { inputs: [], name: "SignatureExpired", type: "error" },
  {
    inputs: [{ internalType: "string", name: "str", type: "string" }],
    name: "StringTooLong",
    type: "error",
  },
  {
    inputs: [
      { internalType: "uint256", name: "expected", type: "uint256" },
      { internalType: "uint256", name: "provided", type: "uint256" },
    ],
    name: "WrongChainId",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: true, internalType: "address", name: "spender", type: "address" },
      { indexed: false, internalType: "uint160", name: "amount", type: "uint160" },
      { indexed: false, internalType: "uint48", name: "expiration", type: "uint48" },
    ],
    name: "Approval",
    type: "event",
  },
  { anonymous: false, inputs: [], name: "EIP712DomainChanged", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "address", name: "token", type: "address" },
      { indexed: false, internalType: "address", name: "spender", type: "address" },
    ],
    name: "Lockdown",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "owner", type: "address" },
      { indexed: true, internalType: "address", name: "token", type: "address" },
      { indexed: true, internalType: "address", name: "account", type: "address" },
      { indexed: false, internalType: "uint160", name: "amount", type: "uint160" },
      { indexed: false, internalType: "uint48", name: "expiration", type: "uint48" },
      { indexed: false, internalType: "uint48", name: "timestamp", type: "uint48" },
    ],
    name: "Permit",
    type: "event",
  },
  {
    inputs: [],
    name: "CHAIN_PERMITS_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "DOMAIN_SEPARATOR",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "NONCES_TO_INVALIDATE_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SIGNED_CANCEL_PERMIT3_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "SIGNED_PERMIT3_TYPEHASH",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "user", type: "address" },
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [
      { internalType: "uint160", name: "amount", type: "uint160" },
      { internalType: "uint48", name: "expiration", type: "uint48" },
      { internalType: "uint48", name: "timestamp", type: "uint48" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "token", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint160", name: "amount", type: "uint160" },
      { internalType: "uint48", name: "expiration", type: "uint48" },
    ],
    name: "approve",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "eip712Domain",
    outputs: [
      { internalType: "bytes1", name: "fields", type: "bytes1" },
      { internalType: "string", name: "name", type: "string" },
      { internalType: "string", name: "version", type: "string" },
      { internalType: "uint256", name: "chainId", type: "uint256" },
      { internalType: "address", name: "verifyingContract", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "uint256[]", name: "extensions", type: "uint256[]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "uint64", name: "chainId", type: "uint64" },
          { internalType: "bytes32[]", name: "salts", type: "bytes32[]" },
        ],
        internalType: "struct INonceManager.NoncesToInvalidate",
        name: "invalidations",
        type: "tuple",
      },
    ],
    name: "hashNoncesToInvalidate",
    outputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      {
        components: [
          { internalType: "bytes32", name: "preHash", type: "bytes32" },
          {
            components: [
              { internalType: "uint64", name: "chainId", type: "uint64" },
              { internalType: "bytes32[]", name: "salts", type: "bytes32[]" },
            ],
            internalType: "struct INonceManager.NoncesToInvalidate",
            name: "invalidations",
            type: "tuple",
          },
          { internalType: "bytes32[]", name: "followingHashes", type: "bytes32[]" },
        ],
        internalType: "struct INonceManager.CancelPermit3Proof",
        name: "proof",
        type: "tuple",
      },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "invalidateNonces",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      {
        components: [
          { internalType: "uint64", name: "chainId", type: "uint64" },
          { internalType: "bytes32[]", name: "salts", type: "bytes32[]" },
        ],
        internalType: "struct INonceManager.NoncesToInvalidate",
        name: "invalidations",
        type: "tuple",
      },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "invalidateNonces",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32[]", name: "salts", type: "bytes32[]" }],
    name: "invalidateNonces",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
    ],
    name: "isNonceUsed",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "token", type: "address" },
          { internalType: "address", name: "spender", type: "address" },
        ],
        internalType: "struct IPermit.TokenSpenderPair[]",
        name: "approvals",
        type: "tuple[]",
      },
    ],
    name: "lockdown",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint48", name: "timestamp", type: "uint48" },
      {
        components: [
          { internalType: "bytes32", name: "preHash", type: "bytes32" },
          {
            components: [
              { internalType: "uint256", name: "chainId", type: "uint256" },
              {
                components: [
                  { internalType: "uint48", name: "modeOrExpiration", type: "uint48" },
                  { internalType: "address", name: "token", type: "address" },
                  { internalType: "address", name: "account", type: "address" },
                  { internalType: "uint160", name: "amountDelta", type: "uint160" },
                ],
                internalType: "struct IPermit3.AllowanceOrTransfer[]",
                name: "permits",
                type: "tuple[]",
              },
            ],
            internalType: "struct IPermit3.ChainPermits",
            name: "permits",
            type: "tuple",
          },
          { internalType: "bytes32[]", name: "followingHashes", type: "bytes32[]" },
        ],
        internalType: "struct IPermit3.Permit3Proof",
        name: "proof",
        type: "tuple",
      },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "permit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "bytes32", name: "salt", type: "bytes32" },
      { internalType: "uint256", name: "deadline", type: "uint256" },
      { internalType: "uint48", name: "timestamp", type: "uint48" },
      {
        components: [
          { internalType: "uint256", name: "chainId", type: "uint256" },
          {
            components: [
              { internalType: "uint48", name: "modeOrExpiration", type: "uint48" },
              { internalType: "address", name: "token", type: "address" },
              { internalType: "address", name: "account", type: "address" },
              { internalType: "uint160", name: "amountDelta", type: "uint160" },
            ],
            internalType: "struct IPermit3.AllowanceOrTransfer[]",
            name: "permits",
            type: "tuple[]",
          },
        ],
        internalType: "struct IPermit3.ChainPermits",
        name: "chain",
        type: "tuple",
      },
      { internalType: "bytes", name: "signature", type: "bytes" },
    ],
    name: "permit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          { internalType: "address", name: "from", type: "address" },
          { internalType: "address", name: "to", type: "address" },
          { internalType: "uint160", name: "amount", type: "uint160" },
          { internalType: "address", name: "token", type: "address" },
        ],
        internalType: "struct IPermit.AllowanceTransferDetails[]",
        name: "transfers",
        type: "tuple[]",
      },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "from", type: "address" },
      { internalType: "address", name: "to", type: "address" },
      { internalType: "uint160", name: "amount", type: "uint160" },
      { internalType: "address", name: "token", type: "address" },
    ],
    name: "transferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
